# -*- coding: utf-8 -*-
"""Montecarlo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dL9Qb_ZwMHdxcucX465KX_YnYlOSFS-0
"""

!pip  install yfinance

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf
from scipy.optimize import minimize
import statsmodels.api as sm

tickers = [
    "RELIANCE.NS",    # Energy / Conglomerate
    "TCS.NS",         # Information Technology
    "HDFCBANK.NS",    # Banking / Financial Services
    "SUNPHARMA.NS",   # Healthcare / Pharma
    "MARUTI.NS"       # Automobile
]

start_date = "2019-01-01"
end_date = "2024-01-01"

data = yf.download(
    tickers,
    start=start_date,
    end=end_date,
    auto_adjust=True,
    group_by="column"
)["Close"]

# Remove rows with missing values
data = data.dropna()

print("Data shape:", data.shape)
print("Start date:", data.index.min())
print("End date:", data.index.max())
print("\nFirst 5 rows:")
print(data.head())
print("\nLast 5 rows:")
print(data.tail())
print("\nMissing values:")
print(data.isna().sum())

"""HISTORICAL PRICE SLOT"""

normalized_data = data / data.iloc[0] * 100

plt.figure(figsize=(12, 6))

for stock in normalized_data.columns:
    plt.plot(normalized_data[stock], label=stock)

plt.title("Normalized Historical Adjusted Closing Prices")
plt.xlabel("Date")
plt.ylabel("Normalized Price Base = 100")
plt.legend()
plt.grid(True)
plt.show()

"""DAILY LOG RETURN

"""

log_returns = np.log(data / data.shift(1)).dropna()

print("Log returns shape:", log_returns.shape)
print("\nFirst 5 rows of log returns:")
print(log_returns.head())

"""RETURN DISTRIBUTION PLOT"""

log_returns.hist(bins=50, figsize=(12, 6))
plt.suptitle("Distribution of Daily Log Returns")
plt.show()

"""STATICAL CALCULATION"""

trading_days = 252
mean_daily_returns = log_returns.mean()
std_daily_returns = log_returns.std()
cov_matrix_daily = log_returns.cov()
corr_matrix_daily = log_returns.corr()
annual_returns = mean_daily_returns * trading_days
annual_volatility = std_daily_returns * np.sqrt(trading_days)
annual_cov_matrix = cov_matrix_daily * trading_days


print("Mean Daily Returns:")
print(mean_daily_returns)

print("\nDaily Standard Deviation:")
print(std_daily_returns)

print("\nDaily Covariance Matrix:")
print(cov_matrix_daily)

print("\nDaily Correlation Matrix:")
print(corr_matrix_daily)

print("\nAnnualized Returns:")
print(annual_returns)

print("\nAnnualized Volatility:")
print(annual_volatility)

"""SUMMARY STATISTICAL TABLE"""

summary_stats = pd.DataFrame({
    "Mean_daily_returns": mean_daily_returns,
    "Std_daily_returns": std_daily_returns,
    "Annual_returns": annual_returns,
    "Annual_volatility": annual_volatility,

})

summary_stats

"""CORRELATION HEATMAP"""

plt.figure(figsize = (8,6))
plt.imshow(corr_matrix_daily, cmap = 'coolwarm', interpolation = 'nearest')
plt.colorbar(label = "correlation")
plt.xticks(range(len(tickers)), tickers, rotation=45)
plt.yticks(range(len(tickers)), tickers)
plt.title('Daily Correlation Matrix')
plt.show()

"""POTFOLIO CONSTRUCTION"""

risk_free_rate = 0.04
def portfolio_return(weights, mean_returns):
    """
    Calculates expected portfolio return.
    Formula: Rp = w' * mu
    """
    return np.dot(weights, mean_returns)


def portfolio_volatility(weights, covariance_matrix):
    """
    Calculates portfolio volatility.
    Formula: sigma_p = sqrt(w' * Sigma * w)
    """
    return np.sqrt(np.dot(weights.T, np.dot(covariance_matrix, weights)))


def sharpe_ratio(weights, mean_returns, covariance_matrix, risk_free_rate):
    """
    Calculates Sharpe Ratio.
    Formula: Sharpe = (Rp - Rf) / sigma_p
    """
    ret = portfolio_return(weights, mean_returns)
    vol = portfolio_volatility(weights, covariance_matrix)

    return (ret - risk_free_rate) / vol

"""EQUAL-WEIGHT PORTFOLIO"""

n_assets = len(tickers)

equal_weights = np.array([1 / n_assets] * n_assets)

equal_return = portfolio_return(equal_weights, annual_returns)

equal_volatility = portfolio_volatility(
    equal_weights,
    annual_cov_matrix
)

equal_sharpe = sharpe_ratio(
    equal_weights,
    annual_returns,
    annual_cov_matrix,
    risk_free_rate
)

print("Equal-Weight Portfolio")
print("----------------------")
print("Weights:", equal_weights)
print("Expected Annual Return:", equal_return)
print("Annual Volatility:", equal_volatility)
print("Sharpe Ratio:", equal_sharpe)

"""IMPORT OPTIMIZER"""

from scipy.optimize import minimize

"""MEAN-VARIANCE OPTIMIZED PORTFOLIO
# Maximum Sharpe Ratio Portfolio
"""

def negative_sharpe_ratio(weights, mean_returns, covariance_matrix, risk_free_rate):
    """
    scipy.optimize.minimize minimizes functions.
    To maximize Sharpe Ratio, we minimize the negative Sharpe Ratio.
    """
    return -sharpe_ratio(weights, mean_returns, covariance_matrix, risk_free_rate)


constraints = ({
    "type": "eq",
    "fun": lambda weights: np.sum(weights) - 1
})

bounds = tuple((0, 1) for stock in range(n_assets))

initial_guess = equal_weights

max_sharpe_result = minimize(
    negative_sharpe_ratio,
    initial_guess,
    args=(annual_returns, annual_cov_matrix, risk_free_rate),
    method="SLSQP",
    bounds=bounds,
    constraints=constraints
)

max_sharpe_weights = max_sharpe_result.x

max_sharpe_return = portfolio_return(
    max_sharpe_weights,
    annual_returns
)

max_sharpe_volatility = portfolio_volatility(
    max_sharpe_weights,
    annual_cov_matrix
)

max_sharpe_value = sharpe_ratio(
    max_sharpe_weights,
    annual_returns,
    annual_cov_matrix,
    risk_free_rate
)

print("Mean-Variance Optimized Portfolio")
print("---------------------------------")
print("Weights:", max_sharpe_weights)
print("Expected Annual Return:", max_sharpe_return)
print("Annual Volatility:", max_sharpe_volatility)
print("Sharpe Ratio:", max_sharpe_value)

"""MINIMUM VOLATILITY PORTFOLIO"""

def minimum_volatility_objective(weights, covariance_matrix):
    """
    Objective function for minimum volatility portfolio.
    """
    return portfolio_volatility(weights, covariance_matrix)


min_vol_result = minimize(
    minimum_volatility_objective,
    initial_guess,
    args=(annual_cov_matrix,),
    method="SLSQP",
    bounds=bounds,
    constraints=constraints
)

min_vol_weights = min_vol_result.x

min_vol_return = portfolio_return(
    min_vol_weights,
    annual_returns
)

min_vol_volatility = portfolio_volatility(
    min_vol_weights,
    annual_cov_matrix
)

min_vol_sharpe = sharpe_ratio(
    min_vol_weights,
    annual_returns,
    annual_cov_matrix,
    risk_free_rate
)

print("Minimum Volatility Portfolio")
print("----------------------------")
print("Weights:", min_vol_weights)
print("Expected Annual Return:", min_vol_return)
print("Annual Volatility:", min_vol_volatility)
print("Sharpe Ratio:", min_vol_sharpe)

"""PORTFOLIO COMPARISON TABLE"""

portfolio_comparison = pd.DataFrame({
    "Portfolio": [
        "Equal Weight",
        "Mean-Variance Optimized",
        "Minimum Volatility"
    ],
    "Expected Annual Return": [
        equal_return,
        max_sharpe_return,
        min_vol_return
    ],
    "Annual Volatility": [
        equal_volatility,
        max_sharpe_volatility,
        min_vol_volatility
    ],
    "Sharpe Ratio": [
        equal_sharpe,
        max_sharpe_value,
        min_vol_sharpe
    ]
})

portfolio_comparison

"""PORTFOLIO WEIGHTS TABLE"""

weights_table = pd.DataFrame({
    "Stock": tickers,
    "Equal Weight": equal_weights,
    "Mean-Variance Optimized": max_sharpe_weights,
    "Minimum Volatility": min_vol_weights
})

weights_table

"""RISK-RETURN COMPARISON CHART"""

plt.figure(figsize=(8, 6))

plt.scatter(
    portfolio_comparison["Annual Volatility"],
    portfolio_comparison["Expected Annual Return"]
)

for i in range(len(portfolio_comparison)):
    plt.text(
        portfolio_comparison["Annual Volatility"][i],
        portfolio_comparison["Expected Annual Return"][i],
        portfolio_comparison["Portfolio"][i]
    )

plt.title("Risk-Return Comparison of Portfolios")
plt.xlabel("Annual Volatility")
plt.ylabel("Expected Annual Return")
plt.grid(True)
plt.show()

"""MONTE CARLO SIMULATION FUNCTION"""

def run_monte_carlo(
    weights,
    mean_daily_returns,
    cov_matrix_daily,
    num_simulations=10000,
    forecast_days=252,
    initial_portfolio_value=100000,
    random_seed=42
):
    """
    Runs Monte Carlo simulation using multivariate normal returns.
    """

    rng = np.random.default_rng(random_seed)

    simulated_asset_returns = rng.multivariate_normal(
        mean=mean_daily_returns.values,
        cov=cov_matrix_daily.values,
        size=(forecast_days, num_simulations)
    )

    portfolio_daily_returns = simulated_asset_returns @ weights

    portfolio_paths = initial_portfolio_value * np.cumprod(
        1 + portfolio_daily_returns,
        axis=0
    )

    return portfolio_paths, portfolio_daily_returns

"""RUN MONTE CARLO FOR EQUAL-WEIGHT PORTFOLIO"""

num_simulations = 10000
forecast_days = 252
initial_portfolio_value = 100000

weights = equal_weights

portfolio_paths, portfolio_daily_returns = run_monte_carlo(
    weights=weights,
    mean_daily_returns=mean_daily_returns,
    cov_matrix_daily=cov_matrix_daily,
    num_simulations=num_simulations,
    forecast_days=forecast_days,
    initial_portfolio_value=initial_portfolio_value
)

"""SIMULATED PORTFOLIO PATH PLOT"""

plt.figure(figsize=(12, 6))

plt.plot(portfolio_paths[:, :100])

plt.title("Monte Carlo Simulated Portfolio Paths")
plt.xlabel("Trading Days")
plt.ylabel("Portfolio Value")
plt.grid(True)
plt.show()

"""FINAL VALUE DISTRIBUTION"""

final_values = portfolio_paths[-1]

plt.figure(figsize=(10, 6))
plt.hist(final_values, bins=50)

plt.title("Distribution of Simulated Final Portfolio Values")
plt.xlabel("Final Portfolio Value")
plt.ylabel("Frequency")
plt.grid(True)
plt.show()

"""RISK METRICS FUNCTION

"""

def calculate_risk_metrics(portfolio_paths, initial_portfolio_value):
    """
    Calculates expected value, VaR, CVaR, probability of loss,
    and maximum drawdown.
    """

    final_values = portfolio_paths[-1]

    profit_loss = final_values - initial_portfolio_value

    expected_final_value = np.mean(final_values)

    expected_profit_loss = np.mean(profit_loss)

    var_95 = np.percentile(profit_loss, 5)

    var_99 = np.percentile(profit_loss, 1)

    cvar_95 = profit_loss[profit_loss <= var_95].mean()

    cvar_99 = profit_loss[profit_loss <= var_99].mean()

    probability_loss = np.mean(final_values < initial_portfolio_value)

    running_max = np.maximum.accumulate(portfolio_paths, axis=0)

    drawdown = (portfolio_paths - running_max) / running_max

    max_drawdown = drawdown.min(axis=0).mean()

    return {
        "Expected Final Value": expected_final_value,
        "Expected Profit/Loss": expected_profit_loss,
        "VaR 95%": var_95,
        "VaR 99%": var_99,
        "CVaR 95%": cvar_95,
        "CVaR 99%": cvar_99,
        "Probability of Loss": probability_loss,
        "Average Maximum Drawdown": max_drawdown
    }

"""RISK METRICS FOR EQUAL-WEIGHT PORTFOLIO"""

risk_metrics = calculate_risk_metrics(
    portfolio_paths,
    initial_portfolio_value
)

risk_metrics_df = pd.DataFrame(
    risk_metrics.items(),
    columns=["Risk Metric", "Value"]
)

risk_metrics_df

"""VaR AND CVaR VISUALIZATION"""

profit_loss = final_values - initial_portfolio_value

var_95 = risk_metrics["VaR 95%"]
cvar_95 = risk_metrics["CVaR 95%"]

plt.figure(figsize=(10, 6))

plt.hist(profit_loss, bins=50)

plt.axvline(var_95, linestyle="--", label="VaR 95%")
plt.axvline(cvar_95, linestyle="-", label="CVaR 95%")

plt.title("Portfolio Profit/Loss Distribution with VaR and CVaR")
plt.xlabel("Profit / Loss")
plt.ylabel("Frequency")
plt.legend()
plt.grid(True)
plt.show()

"""RISK COMPARISON FOR ALL THREE PORTFOLIOS"""

portfolio_weights = {
    "Equal Weight": equal_weights,
    "Mean-Variance Optimized": max_sharpe_weights,
    "Minimum Volatility": min_vol_weights
}

risk_results = []

for portfolio_name, portfolio_weight in portfolio_weights.items():

    paths, returns = run_monte_carlo(
        weights=portfolio_weight,
        mean_daily_returns=mean_daily_returns,
        cov_matrix_daily=cov_matrix_daily,
        num_simulations=10000,
        forecast_days=252,
        initial_portfolio_value=100000
    )

    metrics = calculate_risk_metrics(
        paths,
        initial_portfolio_value=100000
    )

    metrics["Portfolio"] = portfolio_name

    risk_results.append(metrics)

risk_comparison = pd.DataFrame(risk_results)

risk_comparison = risk_comparison[
    [
        "Portfolio",
        "Expected Final Value",
        "Expected Profit/Loss",
        "VaR 95%",
        "VaR 99%",
        "CVaR 95%",
        "CVaR 99%",
        "Probability of Loss",
        "Average Maximum Drawdown"
    ]
]

risk_comparison

"""MONTE CARLO SCENARIO FUNCTION"""

def run_monte_carlo_scenario(
    weights,
    scenario_mean,
    scenario_cov,
    num_simulations=10000,
    forecast_days=252,
    initial_portfolio_value=100000,
    random_seed=42
):
    """
    Runs Monte Carlo simulation under a specific market scenario.
    """

    rng = np.random.default_rng(random_seed)

    simulated_asset_returns = rng.multivariate_normal(
        mean=scenario_mean,
        cov=scenario_cov,
        size=(forecast_days, num_simulations)
    )

    portfolio_daily_returns = simulated_asset_returns @ weights

    portfolio_paths = initial_portfolio_value * np.cumprod(
        1 + portfolio_daily_returns,
        axis=0
    )

    return portfolio_paths

"""DEFINE STRESS TEST SCENARIOS"""

normal_mean = mean_daily_returns.values
normal_cov = cov_matrix_daily.values

high_vol_mean = normal_mean
high_vol_cov = normal_cov * 2

bear_mean = normal_mean - 0.001
bear_cov = normal_cov * 1.5

crash_mean = normal_mean - (0.20 / 252)
crash_cov = normal_cov * 3

stress_scenarios = {
    "Normal Market": (normal_mean, normal_cov),
    "High Volatility": (high_vol_mean, high_vol_cov),
    "Bear Market": (bear_mean, bear_cov),
    "Extreme Crash": (crash_mean, crash_cov)
}

"""RUN STRESS TESTING"""

stress_results = []
stress_paths_dict = {}

for scenario_name, scenario_values in stress_scenarios.items():

    scenario_mean, scenario_cov = scenario_values

    stress_paths = run_monte_carlo_scenario(
        weights=equal_weights,
        scenario_mean=scenario_mean,
        scenario_cov=scenario_cov,
        num_simulations=10000,
        forecast_days=252,
        initial_portfolio_value=100000
    )

    metrics = calculate_risk_metrics(
        stress_paths,
        initial_portfolio_value=100000
    )

    metrics["Scenario"] = scenario_name

    stress_results.append(metrics)

    stress_paths_dict[scenario_name] = stress_paths

stress_results_df = pd.DataFrame(stress_results)

stress_results_df = stress_results_df[
    [
        "Scenario",
        "Expected Final Value",
        "Expected Profit/Loss",
        "VaR 95%",
        "VaR 99%",
        "CVaR 95%",
        "CVaR 99%",
        "Probability of Loss",
        "Average Maximum Drawdown"
    ]
]

stress_results_df

"""STRESS TESTING SUMMARY CHART"""

plt.figure(figsize=(10, 6))

plt.bar(
    stress_results_df["Scenario"],
    stress_results_df["Expected Final Value"]
)

plt.title("Expected Final Portfolio Value Under Stress Scenarios")
plt.xlabel("Scenario")
plt.ylabel("Expected Final Portfolio Value")
plt.xticks(rotation=45)
plt.grid(True)
plt.show()

"""SENSITIVITY ANALYSIS: VOLATILITY CHANGES"""

volatility_multipliers = [0.75, 1.0, 1.25, 1.5, 2.0]

volatility_sensitivity_results = []

for multiplier in volatility_multipliers:

    adjusted_cov = cov_matrix_daily.values * multiplier

    paths = run_monte_carlo_scenario(
        weights=equal_weights,
        scenario_mean=mean_daily_returns.values,
        scenario_cov=adjusted_cov,
        num_simulations=10000,
        forecast_days=252,
        initial_portfolio_value=100000
    )

    metrics = calculate_risk_metrics(
        paths,
        initial_portfolio_value=100000
    )

    metrics["Volatility Multiplier"] = multiplier

    volatility_sensitivity_results.append(metrics)

volatility_sensitivity_df = pd.DataFrame(volatility_sensitivity_results)

volatility_sensitivity_df[
    [
        "Volatility Multiplier",
        "Expected Final Value",
        "VaR 95%",
        "CVaR 95%",
        "Probability of Loss",
        "Average Maximum Drawdown"
    ]
]

"""SENSITIVITY ANALYSIS: NUMBER OF SIMULATION PATHS"""

simulation_counts = [1000, 5000, 10000, 20000]

simulation_sensitivity_results = []

for sim_count in simulation_counts:

    paths, returns = run_monte_carlo(
        weights=equal_weights,
        mean_daily_returns=mean_daily_returns,
        cov_matrix_daily=cov_matrix_daily,
        num_simulations=sim_count,
        forecast_days=252,
        initial_portfolio_value=100000
    )

    metrics = calculate_risk_metrics(
        paths,
        initial_portfolio_value=100000
    )

    metrics["Number of Simulations"] = sim_count

    simulation_sensitivity_results.append(metrics)

simulation_sensitivity_df = pd.DataFrame(simulation_sensitivity_results)

simulation_sensitivity_df[
    [
        "Number of Simulations",
        "Expected Final Value",
        "VaR 95%",
        "CVaR 95%",
        "Probability of Loss",
        "Average Maximum Drawdown"
    ]
]

"""SENSITIVITY ANALYSIS: DIFFERENT TIME HORIZONS"""

time_horizons = [63, 126, 252, 504]

horizon_sensitivity_results = []

for horizon in time_horizons:

    paths, returns = run_monte_carlo(
        weights=equal_weights,
        mean_daily_returns=mean_daily_returns,
        cov_matrix_daily=cov_matrix_daily,
        num_simulations=10000,
        forecast_days=horizon,
        initial_portfolio_value=100000
    )

    metrics = calculate_risk_metrics(
        paths,
        initial_portfolio_value=100000
    )

    metrics["Time Horizon"] = horizon

    horizon_sensitivity_results.append(metrics)

horizon_sensitivity_df = pd.DataFrame(horizon_sensitivity_results)

horizon_sensitivity_df[
    [
        "Time Horizon",
        "Expected Final Value",
        "VaR 95%",
        "CVaR 95%",
        "Probability of Loss",
        "Average Maximum Drawdown"
    ]
]

"""SENSITIVITY ANALYSIS: PORTFOLIO WEIGHT ADJUSTMENT"""

custom_weights = np.array([0.30, 0.25, 0.20, 0.15, 0.10])
custom_weights = custom_weights / custom_weights.sum()

custom_paths, custom_returns = run_monte_carlo(
    weights=custom_weights,
    mean_daily_returns=mean_daily_returns,
    cov_matrix_daily=cov_matrix_daily,
    num_simulations=10000,
    forecast_days=252,
    initial_portfolio_value=100000
)

custom_metrics = calculate_risk_metrics(
    custom_paths,
    initial_portfolio_value=100000
)

custom_metrics_df = pd.DataFrame(
    custom_metrics.items(),
    columns=["Metric", "Value"]
)

print("Custom Portfolio Weights:")
print(custom_weights)

custom_metrics_df

"""SENSITIVITY ANALYSIS: CORRELATION SHIFT"""

def adjust_correlation_matrix(corr_matrix, multiplier):
    """
    Adjusts off-diagonal correlations while keeping diagonal values equal to 1.
    """

    adjusted_corr = corr_matrix.copy()

    for i in range(adjusted_corr.shape[0]):
        for j in range(adjusted_corr.shape[1]):
            if i != j:
                adjusted_corr.iloc[i, j] = adjusted_corr.iloc[i, j] * multiplier

    adjusted_corr = adjusted_corr.clip(-0.99, 0.99)

    for i in range(adjusted_corr.shape[0]):
        adjusted_corr.iloc[i, i] = 1.0

    return adjusted_corr


correlation_multipliers = [0.5, 1.0, 1.5]

correlation_sensitivity_results = []

daily_std = log_returns.std()

for multiplier in correlation_multipliers:

    adjusted_corr = adjust_correlation_matrix(
        corr_matrix_daily,
        multiplier
    )

    adjusted_cov = adjusted_corr.copy()

    for i in range(len(tickers)):
        for j in range(len(tickers)):
            adjusted_cov.iloc[i, j] = (
                adjusted_corr.iloc[i, j]
                * daily_std.iloc[i]
                * daily_std.iloc[j]
            )

    paths = run_monte_carlo_scenario(
        weights=equal_weights,
        scenario_mean=mean_daily_returns.values,
        scenario_cov=adjusted_cov.values,
        num_simulations=10000,
        forecast_days=252,
        initial_portfolio_value=100000
    )

    metrics = calculate_risk_metrics(
        paths,
        initial_portfolio_value=100000
    )

    metrics["Correlation Multiplier"] = multiplier

    correlation_sensitivity_results.append(metrics)

correlation_sensitivity_df = pd.DataFrame(correlation_sensitivity_results)

correlation_sensitivity_df[
    [
        "Correlation Multiplier",
        "Expected Final Value",
        "VaR 95%",
        "CVaR 95%",
        "Probability of Loss",
        "Average Maximum Drawdown"
    ]
]

"""OPTIONAL REGRESSION MODEL WITH NIFTY 50"""

import statsmodels.api as sm

nifty_data = yf.download(
    "^NSEI",
    start=start_date,
    end=end_date,
    auto_adjust=True
)["Close"]

nifty_data = nifty_data.dropna()

nifty_returns = np.log(nifty_data / nifty_data.shift(1)).dropna()

portfolio_historical_returns = log_returns @ equal_weights

regression_data = pd.concat(
    [portfolio_historical_returns, nifty_returns],
    axis=1
).dropna()

regression_data.columns = ["Portfolio_Return", "NIFTY_Return"]

X = regression_data["NIFTY_Return"]
y = regression_data["Portfolio_Return"]

X = sm.add_constant(X)

regression_model = sm.OLS(y, X).fit()

print(regression_model.summary())

"""SAVE FINAL RESULTS"""

data.to_csv("historical_stock_prices.csv")
log_returns.to_csv("daily_log_returns.csv")
summary_stats.to_csv("summary_statistics.csv")
portfolio_comparison.to_csv("portfolio_comparison.csv", index=False)
weights_table.to_csv("portfolio_weights.csv", index=False)
risk_comparison.to_csv("risk_comparison.csv", index=False)
stress_results_df.to_csv("stress_test_results.csv", index=False)
volatility_sensitivity_df.to_csv("volatility_sensitivity.csv", index=False)
simulation_sensitivity_df.to_csv("simulation_sensitivity.csv", index=False)
horizon_sensitivity_df.to_csv("time_horizon_sensitivity.csv", index=False)
correlation_sensitivity_df.to_csv("correlation_sensitivity.csv", index=False)
regression_data.to_csv("regression_data.csv")

print("All result files saved successfully.")